### ISSUE TITLE
afl-multicore add <num> doesn't work correctly

### ISSUE THREAD

**Issue by praseodym** [rc0r/afl-utils#20]
If I have a number of afl-fuzz instances running and want to add some more, `afl-multicore add <num>` will complain that "It seems you're already running an afl-multicore session with name 'SESSION'". After stopping all running fuzzers, `afl-multicore add <num>` will start `<num>` fuzzers without restarting the original ones.

Instead of this behaviour, it should either 1) add new instances without having to stop the session, or 2)  (re)start all instances when adding new ones.

**Comment by rc0r** [comment]
With the new functionality `check_session` must not be called, otherwise adding new afl instances will fail in normal mode. Interactive screen mode is not affected.

@praseodym May I ask you to check out the updated `experimental` branch and test this a bit?

**Comment by praseodym** [comment]
The `experimental` branch works fine from what I can see :)

**Comment by praseodym** [comment]
Although it looks like the `add` breaks the pgid file. Possible solution: have afl-multikill read pgid's from the pgid file in a loop (like it was with pid's) and then append the new pgid instead of overwriting the pgid file.

**Comment by rc0r** [comment]
Should be fixed in experimental.
