### ISSUE TITLE
Feature request: afl-multicore test mode

### ISSUE THREAD

**Issue by praseodym** [rc0r/afl-utils#21]
Now that afl-multicore uses a configuration file, I find myself switching between afl-fuzz and editing the multicore config file to make adjustments. It would be nice if afl-multicore would have a test mode that spawns a single afl-fuzz instance in interactive mode, preferably using a temporary output directory (as to not destroy any current queue files).

**Comment by rc0r** [comment]
Should be fairly easy to implement sth. like `--test`, ignoring the slave count and writing to `<out-dir>/<temp_session>`.

Did you try `-v` and check the contents of `nohup.out`? This might help in debugging afl invocations in the first place.
Regarding the problem of spoiling current output dirs: Setting a temporary session name in the config and afterwards `rm`'ing `<out-dir>/<temp_session>*` might keep your existing queues untouched.

**Comment by praseodym** [comment]
`-v` works, but running full interactive mode usually works a little better to see what's going on. The temporary session name is a good idea, too bad I need to edit the config file for it.

**Comment by rc0r** [comment]
I'll look into it. Maybe we could come with a solution that automagically aborts the test run, reports the outcome to the user and removes the temporary working dir.
But I'm not sure if that's feasible without overcomplicating things...

**Comment by rc0r** [comment]
@praseodym Updated `experimental` with a very simple test mode; feedback appreciated.

**Comment by praseodym** [comment]
Cheers! Seems to work nicely. The screen requirement is a bit weird with only one instance, but it's definitely a useful feature already :smiley:

**Comment by rc0r** [comment]
Yes indeed, this screen requirement is annoying, so I removed it in 8b06322. This also would allow for auto-cleanup of the test output directory. But I'm not sure, that's a good idea for all use cases?!

Thoughts?

**Comment by praseodym** [comment]
I like not removing the output directory automatically, thanks!
