### ISSUE TITLE
Minor bug in afl-multicore

### ISSUE THREAD

**Issue by bshastry** [rc0r/afl-utils#34]
Hi,

In the latest release, python throws a key error when "interactive" is not defined in job configuration file. The patched check simply makes the if statement consistent with other uses.

Cheers,
Bhargava

def write_pgid_file(conf_settings):
    print("")
//   if not conf_settings["interactive"]:
     if "interactive" in conf_settings and conf_settings["interactive"]:

**Comment by rc0r** [comment]
Thanks! Will be fixed in the next release.

**Comment by bshastry** [comment]
I suppose a cleaner patch for this would be:

if not "interactive" in conf_settings or not conf_settings["interactive"]:

cos then, even if the user hasn't explicitly defined "interactive" in the config file, you won't skip past the code that writes pgid to disk.
