### ISSUE TITLE
Feature request: fuzzer program

### ISSUE THREAD

**Issue by bshastry** [rc0r/afl-utils#35]
Hi,

I was wondering if you could support a custom fuzzer program in your job config file in an upcoming release? The use case I am thinking of is doing A/B testing between afl and aflfast. I can wrap your support inside [Orthrus][1].

Cheers,
Bhargava

Something like:

[
...
"fuzzer_prog" : "afl" // OR "aflfast"
..
]

that would be picked up by afl_path, like so:

if "fuzzer_prog" in conf_settings:
  afl_path = shutil.which(conf_settings["fuzzer_prog"])

I suppose afl-utils already supports optional args to AFL via "afl_margs", so fine tuned fuzzing shouldn't be a problem.

[1]: https://github.com/test-pipeline/orthrus

**Comment by rc0r** [comment]
Nice idea! Yeah, I think this should be doable.

**Comment by rc0r** [comment]
Alright, implemented this on [experimental](/rc0r/afl-utils/tree/experimental).

@bshastry may I ask you to test this a bit?

**Comment by bshastry** [comment]
Wow, thanks for a quick turnaround! Will test and report back! :-)

**Comment by bshastry** [comment]
Hi @rc0r 

Took me a while to clean up my codebase and test this feature, but I am happy to report that it works as expected. A minor glitch on my system (python dist bug) is that this line in afl-multicore (experimental):

```
try:
    import simplejson as json
except ImportError:
    import json
```

lead to simplejson being imported succesfully but not having any methods defined i.e., dir(simplejson) shows no methods (I have simplejson 3.8.2)...

This lead to the json.load aborting. Fixed this temporarily on my local installation by forcing import json (using native python json lib).

**Comment by rc0r** [comment]
Thanks for your feedback @bshastry!

This simplejson bug is strange. I do have 3.8.2 as well and it is behaving normal.
