### ISSUE TITLE
Implement multi-master mode

### ISSUE THREAD

**Issue by rc0r** [rc0r/afl-utils#36]
Support multi-master mode in `afl-multicore`.

Replace `slave_only=<bool>` in config file with `master_instances=<int>`
* `master_instances` not specified in config: default to **single master mode**
* `master_instances = 0`: **slave only mode**
* `master_instances = 1`: **single master mode**
* `master_instances > 1`: **multi-master mode**

**Comment by fgeek** [comment]
After testing this in two fuzzing projects I can confirm that the changes are working as expected. Another fuzzing project is finished and another one is still processing, but zero problems regarding afl-utils.
