### ISSUE TITLE
"Slave_only" config setting not working as expected

### ISSUE THREAD

**Issue by bshastry** [rc0r/afl-utils#37]
Hi @rc0r 

So I am trying out the "slave_only" setting as documented. Here's my use case:

```
$ cat asan.conf
...
"slave_only": true
...
$ cat harden.conf
...
"slave_only": false
...

$ afl-multicore -c harden.conf start 2
$ afl-multicore -c asan.conf add 2
```

but then I notice 2 sets of master/slave afl instances. I was expecting 1 master/ 1 slave (harden.conf), and 2 slaves (asan.conf). Am I not doing something right?

Thanks!

**Comment by rc0r** [comment]
`slave_only` was dropped in afl-utils v1.32a (not yet released, but implemented in experimental branch in commit [b39c41b](https://github.com/rc0r/afl-utils/commit/b39c41bcd20d8591da821b2320a3f8138f62b8bd)) in favor of `master_instances`. See #36 for details or updated `README.md` on experimental.

If you're not using the latest version from experimental this may be a real bug.

**Comment by rc0r** [comment]
So for your specific use case, you'd want to change your configs to:

asan.conf:
```json
"master_instances": 1
```
In the above case you may omit `master_instances`. If not present, `afl-multicore` will default to single-master mode.

harden.conf
```json
"master_instances": 0
```

**Comment by bshastry** [comment]
Thanks a ton. I will update my code accordingly. Another issue I have noticed is that on resuming old slave-only sessions, new afl sync subdirs are created, like so:

```
# old 1 master (harden.conf) 2 slave-only (asan.conf)
$ ls
HARDEN000 ASAN001 ASAN002
# On afl-multicore -c asan.conf resume 2
$ ls
HARDEN000 ASAN001 ASAN002 ASAN003 ASAN005
```

I was hoping the resume would reuse old sub dirs. Is this expected?

**Comment by rc0r** [comment]
This is not supposed to happen.

Did you fully terminate the asan fuzzing instances (`ASAN001` and `ASAN002`)?

Another strange thing is that the newly created slaves do not have consecutive job numbers jumping from `ASAN003` to `ASAN005`.

If you're using interactive screen mode, make sure to start `afl-multicore` from the first window with no other windows present in the current screen session. This should in most cases avoid screen hickups. However I doubt this screen thingy has sth. to do with the problem you're seeing.

If this problem persists, I'd need to setup a minimal config like yours to reproduce the issue.

Thanks for your valuable feedback! :)

**Comment by bshastry** [comment]
Sorry, this was a bug in my code. Turns out, I was doing `start` followed by `resume` for the master config but `add` followed by another `add` (instead of `resume`) for the slave config. After the fix, the workflow works as expected :+1: 

I am closing this issue...
