### ISSUE TITLE
Feature request: Automating -T banner to include the fuzzer ID

### ISSUE THREAD

**Issue by fgeek** [rc0r/afl-utils#39]
Would it be possible to automate -T banner to include the fuzzer ID? This could be useful in crash triage process e.g. when several fuzzers started with afl-multicore finds crashes and you are monitoring them inside screen.

**Comment by rc0r** [comment]
Yes, we could implement `@@` or something similar for the banner field in the config field which then gets replaced by the session id of the fuzzer.

**Comment by rc0r** [comment]
@fgeek Did you try omitting `-T banner` when providing a session name via the config file?

```json
    ...
    "session": "sess_name",
    ...
```
This way the fuzzer id (aka session name plus numeric postfix) is displayed in every afl instance. Not sure if that's what you were asking for...

**Comment by fgeek** [comment]
This is exactly what I meant :) :+1:
