### ISSUE TITLE
afl-minimize QEMU mode

### ISSUE THREAD

**Issue by Isaac0616** [rc0r/afl-utils#43]
Is there currently any mechanism to tell the `afl-cmin` and `afl-tmin` to run with the argument `-Q`?

**Comment by rc0r** [comment]
Hi,
recent versions did not allow to specify `-Q` to enable QEMU support. However I added this feature to [experimental](https://github.com/rc0r/afl-utils/tree/experimental).

Check this out and please let me know if this solves the issue. :)

**Comment by Isaac0616** [comment]
Thanks for the update. I have tried the new version and found some issues.
`cmin_cmd += "-Q"` and `tmin_cmd += "-Q"` 
should append a white space after Q like
`cmin_cmd += "-Q "` and `tmin_cmd += "-Q "`

Besides, I recommend also update `print_ok` message of these two commends to reflect the options like `--cmin-qemu`, `--cmin-mem-limit`, and `--cmin-timeout`.

**Comment by rc0r** [comment]
Silly me... Please try again. :)

**Comment by Isaac0616** [comment]
It solves my problem. Thanks a lot.
