### ISSUE TITLE
Setup.py fails 

### ISSUE THREAD

**Issue by blindfuzzy** [rc0r/afl-utils#45]
$ python setup.py 
Traceback (most recent call last):
  File "setup.py", line 17, in <module>
    from setuptools import setup
ImportError: No module named setuptools

Any thoughts as to why this is happening?

**Comment by rc0r** [comment]
Which Python version did you use? `afl-utils` supports Python 3 only.

**Comment by blindfuzzy** [comment]
$ python3  setup.py install
Traceback (most recent call last):
  File "setup.py", line 17, in <module>
    from setuptools import setup
ImportError: No module named 'setuptools'

**Comment by blindfuzzy** [comment]
I tried all the versions of python I had if that helps any.
