### ISSUE TITLE
Event-based twitter updates?

### ISSUE THREAD

**Issue by qhdwns123** [rc0r/afl-utils#50]
I have a question.

Does the afl-stats tool have the ability to tweet when a new crash file is encountered?

**Comment by rc0r** [comment]
Hi,
currently afl-stats uses a fixed time interval to check `fuzzer_stats` and post a summary to Twitter. So reacting on certain events like new paths or crashes found etc. is not supported.

Feel free to add that feature yourself and open a PR. Shouldn't be too hard to do it. In case you go for it make sure to read [docs/CONTRIBUTING.md](https://github.com/rc0r/afl-utils/blob/master/docs/CONTRIBUTING.md)! ;)
