### ISSUE TITLE
write: Broken Pipe when using afl-multicore in interactive mode

### ISSUE THREAD

**Issue by Fitblip** [rc0r/afl-utils#52]
Greetings!

First of all, thanks for building such a great set of tools to manage AFL jobs, I know quite a few folks who have written hacky versions themselves, and while that works, something OSS is much better!

I seem to be running into an issue when trying to launch multiple AFL instances in interactive mode, for some reason the master session works great, but all the slaves are dead on launch, and in the window that I launched stuff from I see `write: Broken pipe`

![image](https://user-images.githubusercontent.com/1072598/31144595-179b6c0a-a836-11e7-9c48-99c7166f217b.png)

Here's my multicore conf:

```
{
    "input": "../test_cases",
    "output": "../fuzzing",
    "target": "../REDACTED",
    "cmdline": "-r @@",
    "interactive": true
}
```

Any suggestions?

**Comment by fgeek** [comment]
On what platform? Quick fix might be using -s 30 or similar.

**Comment by Fitblip** [comment]
Hey @fgeek - thanks for the advice! I believe that should fix it - I pulled the multicore command apart and ended up executing my job in a bash script to do the same thing, and noticed I needed a delay for it to work properly. 

Maybe it'd be worth having it do that by default? Do you know if it's common to need to do that on other platforms?

If you're still curious, here's my box's info (a google cloud ubuntu 16.04 instance):

```
ryan@fuzzbox:~$ uname -a
Linux fuzzbox 4.10.0-35-generic #39~16.04.1-Ubuntu SMP Wed Sep 13 09:02:42 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

ryan@fuzzbox:~$ screen -v
Screen version 4.03.01 (GNU) 28-Jun-15

ryan@fuzzbox:~$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.3 LTS"
```

**Comment by rc0r** [comment]
Hi @Fitblip,

whether or not it is necessary to delay the starting of afl instances depends heavily on both your target and your initial corpus size. The problem can be reproduced quite reliably when resuming sessions with a very large queue. Afl's init phase takes quite some time (depending on the number of queue entries and the time needed to process a single sample) in that case. During that phase the different (independent) afl instances interfere with each other quite heavily. I can't remember the reason right now. File I/O is involved certainly, but it's not the only reason... I think the problem itself was discussed on the afl-users ML. If interested you could check the archives. Someone called the phenomenon "thundering herd", so you might want to try searching for that. ;)

That said, I think using some arbitrary delay value as a default makes not much sense. It might be good for one specific use case, but may be completely useless for another one. However there's `-s auto`. It uses a very conservative and naive approach to guesstimate the required delay. See [afl_multicore.py:271](https://github.com/rc0r/afl-utils/blob/1a10e7bc40d95243c4cbb1eb9602efc51dc06663/afl_utils/afl_multicore.py#L271) for details how it's calculated.

HTH

**Comment by Fitblip** [comment]
Excellent, thanks for the info @rc0r. 

Feel free to close this ticket!
