### ISSUE TITLE
Parallelize afl-tmin invocation

### ISSUE THREAD

**Issue by rc0r** [rc0r/afl-utils#8]
Running `afl-tmin` on large corpora can take days, so running multiple `afl-tmin` instances in parallel might give some good speed-up.

**Comment by numist** [comment]
Yes please.

**Comment by rc0r** [comment]
Here you go, check out the `experimental` branch that contains improvements and new features for version 1.14a. I just added parallel `afl-tmin` invocation.

Please let me know, if this works for you. I just a ran a single quick test so far. So bug reports are welcome!

**Comment by numist** [comment]
```
Starting afl-tmin worker 0.
Starting afl-tmin worker 1.
Starting afl-tmin worker 2.
Starting afl-tmin worker 3.
```

Nice. This is still going to take a few days to finish, but at least I don't have to handcraft my own `parallel` invocations anymore~
